<%
Const SysRootDir = "/"
Const SiteDataPath = "Database/Database.mdb"
Const SiteDataBakPath = "Database/Database_bak.mdb"
Const StatDataPath = "Database/Stat.mdb"
Const StatDataBakPath = "Database/Stat_bak.mdb"
Const EnableStopInjection = True
Const Kill_ip = True
Const Refresh = 5
Const NewInfo = 12
Const ProInfo = 15
Const JobInfo = 12
Const DownInfo = 12
Const OtherInfo = 12
Const MessageInfo = 8
Const ISHTML = 1
Const HTMLName = ""
Const NewSortName = "NewClass"
Const NewName = "New"
Const ProSortName = "?Page"
Const ProName = "Product"
Const DownSortName = "DownloadClass"
Const DownNameDiy = "Download"
Const OtherSortName = "InfoClass"
Const OtherName = "Info"
Const JobSortName = "JobClass"
Const JobNameDiy = "Job"
Const AboutNameDiy = "About"
Const Separated = "="
%>