<%
Const SiteName=""        '网站名称
Const SiteTitle=""        '网站标题
Const SiteName2=""        '公司名称
Const Siteadd=""        '公司地址
Const Siteno=""        '公司地址
Const Sitetel=""        '公司电话
Const Sitefax=""        '公司传真
Const Sitetel2=""        '公司传真
Const SiteUrl=""        '网站地址
Const EnterpriseMail=""        '企业邮局
Const LogoUrl=""        'Logo地址
Const BannerUrl=""        'Banner地址
Const High=200        '高度
Const WebmasterName=""        '站长姓名
Const WebmasterEmail=""        '站长信箱
Const Copyright=""        '版权信息
Const g1=""        '广告位1 (g1)
Const g2=""        '广告位1 (g1)
Const g3=""        '广告位1 (g1)
Const g4=""        '广告位1 (g1)
Const g5=""        '广告位1 (g1)
Const g6=""        '广告位1 (g1)
Const gl1=""        '广告链接1 (gl1)
Const gl2=""        '广告链接1 (gl1)
Const gl3=""        '广告链接1 (gl1)
Const gl4=""        '广告链接1 (gl1)
Const gl5=""        '广告链接1 (gl1)
Const gl6=""        '广告链接1 (gl1)
Const MaxPerPage_Default=10        '首页每页产品或文章数
Const MaxPerPage_Search=10        '文章搜索页每页文章数
Const ShowContentByPage="Yes"        '文章内容是否分页显示
Const MaxPerPage_Content=200000        '每页显示大约字符数
Const EnableArticleCheck="Yes"        '是否启用文章审核功能
Const EnableUploadFile="Yes"        '是否开放文件上传
Const PopAnnounce="Yes"        '是否弹出公告窗口
Const HitsOfHot=500        '热门文章点击数
Const MaxFileSize=200        '上传文件大小限制
Const SaveUpFilesPath="UploadFiles"        '存放上传文件的目录
Const UpFileType="gif|jpg|bmp|png|swf|doc|rar|exe"        '允许的上传文件类型
Const DelUpFiles="Yes"        '删除文章时是否同时删除文章中的上传文件
Const SessionTimeout=10        'Session会话的保持时间
Const MailObject="Jmail"        '邮件发送组件
Const MailServer=""        '用来发送邮件的SMTP服务器
Const MailServerUserName=""        '登录用户名
Const MailServerPassWord=""        '登录密码
Const MailDomain=""        '域名
%>